export enum TypeSubject {
  branch = "sucursales",
  category = "categorias",
  customer = "clientes",
  sale = "ventas",
  input = "entradas",
  kardex = "kardex",
  order = "ordenes",
  permission = "permisos",
  product = "productos",
  presentation = "presentaciones",
  role = "roles",
  staff = "staffs",
  user = "usuarios",
  price = "precios",
  output = "salidas",
  transfer = "transferencias",
  brand = "marcas",
  provider = "proveedores",
  report = "reportes",
  delivery = "entregas",
  inventory = "inventarios",
}